### ISSUE TITLE
Demo does not work in Firefox and Chrome due to content been served via HTTP and HTTPS

### ISSUE THREAD

**Issue by sksbrg** [oribella/aurelia-sortable#1]
Hi,

I'm highly interested to tryout your plugin and wanted to start by having a look at the demo first. But it seems to neither work in actual Firefox nor Chrome due to Flickr data been served via HTTP while demo itself uses HTTPS.

Firefox:
> Blocked loading mixed active content "http://api.flickr.com/services/feeds/photos_public.gne?tags=mountain&tagmode=any&format=json&jsoncallback=jsonp_callback_33017"
https://oribella.github.io/aurelia-sortable/#
Line 10

Chrome:
>Mixed Content: The page at 'https://oribella.github.io/aurelia-sortable/' was loaded over HTTPS, but requested an insecure script 'http://api.flickr.com/services/feeds/photos_public.gne?tags=mountain&tagmode=any&format=json&jsoncallback=jsonp_callback_5467'. This request has been blocked; the content must be served over HTTPS

Remark: Internet Explorer 11 did allow me to view "insecure" content easily. So after a first look I think your plugin provides exactly what I need right now :+1:

**Comment by stoffeastrom** [comment]
Thank for you input. I have been accessing it via `http` so didn't notice that.

http://oribella.github.io/aurelia-sortable
