### ISSUE TITLE
Aurelia-bundler breaks sortable

### ISSUE THREAD

**Issue by Souldrinker** [oribella/aurelia-sortable#10]
When I try out my code I mainly run unbundled and has successfully been using aurelia-sortable. But now when we put out a bundled version of our app in a QA environment we got reports that sorting didn't work and after some investigation it seems like the sortable attribute gets stripped when bundling.

That is if I for example have this code ```<div sortable="items.bind: sortedFavorites" class="myApps_container">``` it gets changed to this inside the bundle ```<div sortable class="myApps_container">```.

If I change the attribute name to sortablex or something else it remains intact and the ```sortable-item="item.bind: favorite"``` remains as it should, so my guess is there might be some conflict with some reserved html attribute (or a bug in the bundler, systemjs or something else).

Any thoughts?

When I bundled I had to add this to my includes to get all oribella stuff bundled:
```
                "aurelia-sortable",
                "aurelia-sortable/sortable"
```

**Comment by stoffeastrom** [comment]
The bundler is using `html-minifier` and a bunch of options more
specifically

`collapseBooleanAttributes` is set to true

which after finding this [issue](
https://github.com/kangax/html-minifier/issues/63)

turns out that `sortable` is consider and stripped?



On Tue, Feb 2, 2016 at 12:33 PM, Tony Olsson <notifications@github.com>
wrote:

> When I try out my code I mainly run unbundled and has successfully been
> using aurelia-sortable But now when we put out a bundled version of our app
> in a QA environment we got reports that sorting didn't work and after some
> investigation it seems like the sortable attribute gets stripped when
> bundling
>
> That is if I for example have this code <div sortable="itemsbind:
> sortedFavorites" class="myApps_container"> it gets changed to this inside
> the bundle <div sortable class="myApps_container">
>
> If I change the attribute name to sortablex or something else it remains
> intact and the sortable-item="itembind: favorite" remains as it should,
> so my guess is there might be some conflict with some reserved html
> attribute (or a bug in the bundler, systemjs or something else)
>
> Any thoughts?
>
> When I bundled I had to add this to my includes to get all oribella stuff
> bundled:
>
>                 "aurelia-sortable",
>                 "aurelia-sortable/sortable"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oribella/aurelia-sortable/issues/10>.
>



-- 

Telefon arbete : +46 (0) 10 209 77 96

Telefon mobil  : +46 (0) 733 50 62 94

**Comment by Souldrinker** [comment]
Ah, perfect, that was the issue. At first I was afraid I had to turn off the minify completely in my bundle which increased the file size from 168kb to 278kb for my app (excluding external libs), but then I saw I could do like this in my bundle config:
```
            options: {
                inject: true,
                minify: true,
                htmlminopts: { collapseBooleanAttributes: false }
            }
```
...which made the file size stay the same but didn't collapse the sortable attribute :-)

**Comment by stoffeastrom** [comment]
I think we should rename the attribute. Adding a prefix for example
`oa-sortable` or similar...

Thoughts?

**Comment by Souldrinker** [comment]
Yes, I was going to suggest changing the attribute name before I found the option to disable the collapsing, but still it might be a good idea to avoid confusion and having to add special configurations to the bundling. So at least for me I'm all for a name change.

**Comment by gavinaiken** [comment]
seems to make sense in order to avoid obscure problems!
