### ISSUE TITLE
error after installation

### ISSUE THREAD

**Issue by robertogonzalezdelarosa** [oribella/aurelia-sortable#11]
HI i got this error after installation 

Unhandled promise rejection Error: Error invoking SVGAnalyzer. 

I just installed the plugin and set it in main.js as described in the docs.

**Comment by stoffeastrom** [comment]
Can you run Aurelia without the plugin? This error message seems to come from Aurelia? Are you using the `skeleton-navigation`? With what version of `jspm` did you install Aurelia and then this plugin with?

**Comment by stoffeastrom** [comment]
I updated the `README.md` since it's now possible to install it through `npm` also notice how to register it in `main.js`. This needs to map how you've install the plugin, so make sure to check your `config.js`

**Comment by robertogonzalezdelarosa** [comment]
Correct I can run aurelia without the plugin. Im using "jspm": "^0.16.11" version.

**Comment by stoffeastrom** [comment]
Can you reproduce this in a [plnkr](http://bit.ly/aurelia-plunker) or similar else it's a bit hard to know what is going on.

Which version of the plugin did you install? I wonder if you got the `master` since you did install it through `jspm:github...`

**Comment by robertogonzalezdelarosa** [comment]
I got the lastest version. 
But I will update aurelia framwork to latest version also maybe is what i need

**Comment by robertogonzalezdelarosa** [comment]
problem solved. An aurelia framework updated  was requiered thanks.

**Comment by robertogonzalezdelarosa** [comment]
it works like a charm!. thank you very much for this plugin!!!.

**Comment by stoffeastrom** [comment]
:+1:
