### ISSUE TITLE
Displacement of tiles below the fold

### ISSUE THREAD

**Issue by minro** [oribella/aurelia-sortable#12]
Given a refresh of the page/div/area with sortable items, and the page/div/area is not tall enough to house all items in view, scrolling down below "the fold" and trying to move the items from there, items will be displaced while moving as well as when dropped.

Tested this with version ^0.5.3 and 0.4.0.

I've created this repro based on Aurelia-typescript-skeleton

Here's a screen grab: trying to move anything from tile 15 and down will demonstrate the issue: http://imgur.com/UKmjf8h

However this does not seem to be a problem in your demo: 
http://oribella.github.io/aurelia-sortable/

I wonder why this is happening in mine

**Comment by minro** [comment]
However this does not seem to be a problem in your demo: 
http://oribella.github.io/aurelia-sortable/

I wonder why this is happening in mine

**Comment by gavinaiken** [comment]
I think this sounds like the same issue I had, see https://github.com/oribella/aurelia-sortable/issues/8

The solution for me was to set an element of the DOM to be the scroll container for the page, and ensure that container was absolute positioned and 100% width/height. Here's the CSS I used for that element:

```css
.body-wrapper {
    overflow-x: hidden;
    overflow-y: auto;
    position: absolute;
    top: 0;
    bottom: 0;
    height: 100%;
    width: 100%;
}
```

and then in the sortable item I configured it to use that div as the scroll item like so:

```html
<ul sortable="items.bind: config.widgets; scroll.bind: '.body-wrapper'" class="list-unstyled">
```

**Comment by minro** [comment]
This works well in my repro, I lost the "ghost image" that I'm moving, but it still moves correctly. 
It doesn't work in my actual project dom structure but that may be the result of something else. Will investigate. Thanks for helping Gavin.

**Comment by stoffeastrom** [comment]
Yes, that sounds like you haven't configured the correct scroll element.. Have you tried adding overflow-x: auto; on the container class?

**Comment by minro** [comment]
It may be that I'm doing something wrong that I'm failing to spot, but this is my simple layout and styling example, this renders a displacement of the ghost when grabbing a tile/item/card from beneath the visible view. I have also tried setting the .page-host styling "hack" that @gavinaiken mentions in #8 . 

This layout is also close to identical to the layout in your demo example. One thing I have seen is that I don't get the placeholder-class show up on the element that is moved, I'm using the default placeholder mechanism.

I've upped the last build I have here: [repro](https://github.com/minro/aurelia-sortable.git) if you have the time and are able to spot anything obvious.

```
<style>
* { box-sizing: border-box; }

.page-host {
  position: absolute;
  left: 0;
  right: 0;
  top: 20em;
  bottom: 0;
  overflow-x: hidden;
  overflow-y: auto;
}

.top {
  height: 20em;
}

.item {
  width: 20%;
  height: 3em;
  padding: 16px;
  margin: 16px;
  position: relative;            
  border: 2px solid red;
  float: left;
}
</style>

```
```
<body>
  <div class="top">
    <div class="page-host">
      <router-view>
        <div class="container" sortable="scroll.bind: '.page-host'; items.bind: cards;">
          <div class="item" sortable-item="item.bind: card">
          ...
```

**Comment by stoffeastrom** [comment]
The only thing I see just looking at the code you pasted is that you have
to make sure that the scroll container has the correct height

height: 100%;width: 100%;


in your case it should be the height of the viewport e.g browser and not
the whole scrollable content if that make sense

**Comment by minro** [comment]
Interesting;
without the height + width 100% I can move the tiles around and they will be placed where my mouse is but with the ghost displaced. 

With the height + width 100% the ghost is correctly placed but the actual tile will be placed in the wrong position, of an approximate equal distance lower than target, that I have scrolled.

**Comment by stoffeastrom** [comment]
I have to look at the repro to get some more insight.. Don't know when l'll have time though so report back IF you make any progress

**Comment by stoffeastrom** [comment]
So I look a bit at the repro and the problem is that you are using `margin` which won't work with the `getBoundingClientRect`. The plugin is using the `getBoundingClientRect` to be able to calculate where to position the drag element and it's also used for other use cases.

**Comment by stoffeastrom** [comment]
Also the `page-host` `getBoundingClientRect` is wrong since it has to contain the `sortable`. Setting a height on `html, body` solves that

**Comment by minro** [comment]
Thank you very much for taking time looking into it, I'll have a look again tomorrow

**Comment by minro** [comment]
So I ran this again updating the layout to match yours even closer. All your suggestions works as long as the sortable area was in the bottom of the page. 

As far as I can tell this sortable library only works as intended if the area that is sortable is the last area on the page,.. and maybe this is what you are talking about in #8 and a fix for this would mean too much code. 

But in present state, the rule of something needing to be the last area of the page, would break most site layouts you want to build, or force some kind of overlay to sort things, or am I missing something again? I have updated the [repro ](https://github.com/minro/aurelia-sortable) with my last code, uncomment the `.bottom` element in `app.html` to break implementation.

Also your comment about margins seems wrong to me since I can add margins to the items(if this is where you hinted to I had margins) with no additional detrimental or improving effect.

**Comment by stoffeastrom** [comment]
That sounds weird but perhaps it's a problem if you have a non SPA app since this seems to happen only for layouts where you have a scroll on the "page". If you have setup your scroll container correctly it shouldnt be a problem

**Comment by minro** [comment]
I don't really want a scroll container, I want your demo example but with content beneath your scrollable area. 

If you wanted a footer inside your demo example `<body>`  after `<.page-host>` how would you do that?

For me the absolute position makes this difficult.

**Comment by stoffeastrom** [comment]
Not sure but about that. I'll have to look into it. Don't know how difficult it would be to support that yet

**Comment by stoffeastrom** [comment]
In that case you need 2 scrolls if I understand you correctly so both on the `.page-host` and for the browser? This kind of scenario is not supported.

**Comment by minro** [comment]
Actually what I want is this

header
some stuff
main-sortable <- this area can be dynamic in height depending on amount of items but without scroll.
other stuff
footer

No-fixed header and footer, aka whole page scrolls. 

If this is unsupported I totally get it. But would have been a nice feature since that's a common layout scenario. 
Will this remain unsupported or is this something that will get implemented? If not I need to find another solution.

**Comment by stoffeastrom** [comment]
Ok, that sounds like #8 and I'm not sure since it would mean a lot of changes. If we could figure out a good solution for it we could add it. PR's welcome.. This needs some more thinking

**Comment by minro** [comment]
I really like the library so I might look into it but until now I haven't really peeked behind the curtains of your code so it might take some time.
Thanks for your patience and quick responses.

**Comment by gavinaiken** [comment]
@minro your scenario sounds a lot like how my page was laid out. I looked into making changes to aurelia-sortable to support that kind of scenario and got probably about half way there but then decided to go with the work-around of the absolute-positioned 100% height/width scrollable area instead. Can give you some clues as to what I tried if it that helps at all.

**Comment by minro** [comment]
Yes you are welcome with any tips but I'm pretty sure positioning something absolutely is a good way to start off bad, in my layout example anyway.

**Comment by stoffeastrom** [comment]
I changed my demo so the whole page scrolls to get some more understanding what to change

- [ ] Need to expose `clientPoints` from the *Oribella* framework to easily support `document.elementFromPoint`

- [ ] Need to separate scrolling element and scroll listener to support hooking up the scroll listener on `document` and use `document.scrollingElement` as the element

- [ ] Special handling for binding `document`

After that we need to verify auto scrollling and manual scrollling

**Comment by stoffeastrom** [comment]
I have a [branch](https://github.com/oribella/aurelia-sortable/tree/feat/document-scroll) experimenting with above. Where I'm also moved in a new demo folder where I plan to put `features` to show off. This enables easier development of the plugin. Basically you will do `npm run dev` and you will be able to run the demo.
