### ISSUE TITLE
Unhandled rejection Error: Script error for "oribella-aurelia-sortable/sortable"

### ISSUE THREAD

**Issue by jaysson** [oribella/aurelia-sortable#16]
<img width="1433" alt="screen shot 2016-08-30 at 1 59 20 am" src="https://cloud.githubusercontent.com/assets/1563862/18066309/74b1347c-6e55-11e6-846a-aa4ba707cb62.png">

I am using Aurelia CLI.

**aurelia.json**

```
"dependencies": [
    ...
    "oribella-aurelia-sortable"
    ...
]
```

**main.ts**

```
aurelia.use
        .standardConfiguration()
        .plugin('aurelia-validation')
        .plugin("oribella-aurelia-sortable")
        .feature('resources');
```

**Comment by stoffeastrom** [comment]
Haven't tried the latest but I think we need to add "build resources" 

```
"aurelia": {
   "build": {
     "resources": [
      "auto-scroll",
      "drag",
      "sortable"
     ]
 },
```
something like that in the `package.json`

**Comment by stoffeastrom** [comment]
Should be enough with 

```
"aurelia": {
  "build": {
    "sortable"
  }
}
```
Can you test that above works? @jaysson

**Comment by jaysson** [comment]
That didn't work.

I added following code to package.json. It didn't work, so added it to aurelia.json again. That did not work either. Is there a demo project with Aurelia CLI?

```

"aurelia": {
    "build": {
      "resources": [
        "sortable"
      ]
    }
 }

```

**Comment by stoffeastrom** [comment]
Havent't used the Aurelia CLI (still in alpha) so I'm not sure what your problem is. Somehow you need to add the plugin to the generated bundle. Have you tried following the [readme](https://github.com/aurelia/cli#a-commonjs-package)?

**Comment by jaysson** [comment]
I did try that. But that throws error while building.

<img width="1346" alt="screen shot 2016-09-15 at 3 28 28 pm" src="https://cloud.githubusercontent.com/assets/1563862/18546016/5a09c614-7b59-11e6-93bc-0538968afb4a.png">

**Comment by stoffeastrom** [comment]
Aha, Since this plugin is dependent on [`default-gestures`](https://github.com/oribella/default-gestures) which has these deps

```
    "oribella-doubletap": "^0.5.0",
    "oribella-framework": "^0.5.0",
    "oribella-longtap": "^0.5.0",
    "oribella-longtap-swipe": "^0.5.0",
    "oribella-pinch": "^0.5.0",
    "oribella-rotate": "^0.5.0",
    "oribella-swipe": "^0.5.0",
    "oribella-tap": "^0.5.0"
```
So I guess you have to add all those to get it working :/ since they don't have the `aurelia` property in their `package.json`.

**Comment by AStoker** [comment]
I think this is related to how the CLI traces it's dependencies. The package json file is pointing to the main file here (https://github.com/oribella/aurelia-sortable/blob/master/dist/commonjs/index.js#L8). But it just says to configure the global resources to use `./sortable.js`. Since it doesn't actually _import_ the sortable library, the aurelia tracer doesn't know to bring in `./sortable.js`, which is why you have a request being sent out for it.

**Comment by stoffeastrom** [comment]
@AStoker that makes sense. How should that be handled?

**Comment by AStoker** [comment]
Well, you already have listed as a dependency in the json file what you need.
What I think you need is to import your dependencies, or somehow let them be found and imported. I'm a bit loaded up at the moment, but I can try and take a peek at it in a day or two.

**Comment by jayrod718** [comment]
I was able to get the build errors to clear up and the page to load cleanly but the sortable tags dont seem to be doing anything. I am using OL/LI and not DIVs, tried switching to divs and it doesnt seem to do anything at all. Here is the package.json that cleared up my build errors, I am using the Aurelia CLI.

`          {
            "name": "oribella-aurelia-sortable",
            "path": "../node_modules/oribella-aurelia-sortable/dist/amd",
            "main": "sortable"
          },
          {
            "name": "oribella-framework",
            "path": "../node_modules/oribella-framework/dist/amd",
            "main": "index"
          },
          {
            "name": "oribella-tap",
            "path": "../node_modules/oribella-tap/dist/amd",
            "main": "index"
          },          
          {
            "name": "oribella-doubletap",
            "path": "../node_modules/oribella-doubletap/dist/amd",
            "main": "index"
          },          
          {
            "name": "oribella-longtap",
            "path": "../node_modules/oribella-longtap/dist/amd",
            "main": "index"
          },          
          {
            "name": "oribella-swipe",
            "path": "../node_modules/oribella-swipe/dist/amd",
            "main": "index"
          },          
          {
            "name": "oribella-longtap-swipe",
            "path": "../node_modules/oribella-longtap-swipe/dist/amd",
            "main": "index"
          },          
          {
            "name": "oribella-pinch",
            "path": "../node_modules/oribella-pinch/dist/amd",
            "main": "index"
          },          
          {
            "name": "oribella-rotate",
            "path": "../node_modules/oribella-rotate/dist/amd",
            "main": "index"
          },
          {
            "name": "oribella-default-gestures",
            "path": "../node_modules/oribella-default-gestures/dist/amd",
            "main": "index"
          }`

**Comment by stoffeastrom** [comment]
@jayrod718 shouldn't matter which tags you use! Do you have any sample that reproduces your problem?

Also, is there something that needs to be done so you don't have to add all the dependency manually like you did above?

**Comment by klaa12924** [comment]
I'm having the same issue as @jayrod718 and tried his solution as well but it's not working for me unfortunatly.
A demo aurelia cli project with the plugin would be much appreciated.

**Comment by klaa12924** [comment]
I have managed to get it working with aurelia cli project:
place the following in your aurelia.json
````
{
    "name": "oribella-aurelia-sortable",
    "path": "../node_modules/oribella-aurelia-sortable/dist/amd",
    "main": "index",
    "resources": [
        "sortable.js",
        "drag.js",
        "auto-scroll.js"
     ]
},
{
    "name": "oribella-framework",
    "path": "../node_modules/oribella-framework/dist/amd",
    "main": "index"
},
{
    "name": "oribella-tap",
    "path": "../node_modules/oribella-tap/dist/amd",
    "main": "index"
},
{
    "name": "oribella-doubletap",
    "path": "../node_modules/oribella-doubletap/dist/amd",
    "main": "index"
},
{
    "name": "oribella-longtap",
    "path": "../node_modules/oribella-longtap/dist/amd",
    "main": "index"
},
{
    "name": "oribella-swipe",
    "path": "../node_modules/oribella-swipe/dist/amd",
    "main": "index"
},
{
    "name": "oribella-longtap-swipe",
    "path": "../node_modules/oribella-longtap-swipe/dist/amd",
    "main": "index"
},
{
    "name": "oribella-pinch",
    "path": "../node_modules/oribella-pinch/dist/amd",
    "main": "index"
},
{
    "name": "oribella-rotate",
    "path": "../node_modules/oribella-rotate/dist/amd",
    "main": "index"
},
{
    "name": "oribella-default-gestures",
    "path": "../node_modules/oribella-default-gestures/dist/amd",
    "main": "index"
}
````

**Comment by stoffeastrom** [comment]
@klaa12924 👍

**Comment by stoffeastrom** [comment]
This should be much easier since there only is 2 dependencies in the latest e.g

`oribella-framework`
`oribella`

Configure according to the CLI
