### ISSUE TITLE
Problem with method moved toIx property

### ISSUE THREAD

**Issue by AmazingDesign** [oribella/aurelia-sortable#18]
Hi!

We are developing our first app in Aurelia and we encountered a problem with toIx property when we try to call moved method. It was always -1. fromIx always had proper value.

We fount that method move sorting item doesn't pass the toIx argument to class parameter.
```
    Sortable.prototype.moveSortingItem = function moveSortingItem(toIx) {
      var fromIx = this.items.indexOf(this.drag.item);
      this.move(fromIx, toIx);
    };
```
After adding one line at the end, seems to be working fine.
```
    Sortable.prototype.moveSortingItem = function moveSortingItem(toIx) {
      var fromIx = this.items.indexOf(this.drag.item);
      this.move(fromIx, toIx);
      this.toIx = toIx;
    };
```

This is a good solution? As I said it is our first app in Aurelia so we want to be sure if we didn't miss something.

**Comment by stoffeastrom** [comment]
Hi @AmazingDesign,

I'm not sure I understand why you are calling the `moved` method yourself? Can you elaborate on how you are using the plugin?

**Comment by AmazingDesign** [comment]
We said it wrong. Ofc we didn't call this method ourselves. It is called when drag of an sortable list object  ends. And it always returns toIx = -1. After change mentioned above it returns proper value.

```
 @bindable moved = args => {
    console.log(args);
}
```

**Comment by stoffeastrom** [comment]
That sounds reasonable. Would you be able to create PR?
