### ISSUE TITLE
Text inputs inside sortable items don't behave correctly

### ISSUE THREAD

**Issue by gavinaiken** [oribella/aurelia-sortable#2]
I've observed two problems with text inputs inside a `sortable-item` in a `sortable` area:

1/ You can't click on the text input to give it focus. You can tab into it, or right-click on it, but a standard click seems to be intercepted by the oribella gestures framework.

2/ You can't drag-select text within a text input to highlight some of the text in it. Instead the whole `sortable-item` starts to drag.

Is there any way to limit the sortable gesture handler to certain areas, e.g. a title bar area of a div? Or to prevent the draggable gesture behaviour from applying to text inputs?

**Comment by stoffeastrom** [comment]
You can bind a `allowDrag` function that gets the element as first parameter. Just return false if it shouldn't be allowed. However, you might need the `native event` to check `event.target`. I can add that as a parameter, thoughts?

**Comment by stoffeastrom** [comment]
Added the `native event` as first parameter to the `allowDrag` function. So you should be able to do something like

```js
allowDrag(e) {
  return e.tagName !== "INPUT";
}

**Comment by gavinaiken** [comment]
Yes that sounds perfect, thanks for the very quick response. It's a great library you've built here!

**Comment by stoffeastrom** [comment]
Oh, I there is an error in above code it should be `event.target.tagName`bug I guess you figure it out.

**Comment by gavinaiken** [comment]
I'm having trouble adding the binding for the `allowDrag`. I assumed I would bind to it like the `moved` handler, e.g.:

```
<ul class="dashboard list-unstyled" sortable="items.bind: widgets; moved.call:moved(); placeholder.bind: { view: 'blank' }; allowDrag.call:allowDrag();">
```

but my allowDrag function isn't getting called. Can you give me any guidance on how to bind it properly?

**Comment by gavinaiken** [comment]
Never mind, I forgot that aurelia converts to snake-case for html attributes so the syntax is this:

```
<ul class="dashboard list-unstyled" sortable="items.bind: widgets; moved.call:moved(); placeholder.bind: { view: 'blank' }; allow-drag.call:allowDrag();">
```

so now it's working, thanks!

**Comment by gavinaiken** [comment]
In fact this is the required syntax it seems!

```
<ul class="dashboard list-unstyled" sortable="items.bind: widgets; moved.call:moved(); placeholder.bind: { view: 'blank' }; allow-drag.bind:allowDrag;">
```

**Comment by stoffeastrom** [comment]
Yes. Since I'm not calling the function with the `eventArgs` property as the first parameter it seems wrong. I will look into this. It would be nice to be able to send in view specific variables in your functions also. 

Fixing that would mean that the current params would end up on the `eventArgs` object instead but I think that's a much better solution.

**Comment by stoffeastrom** [comment]
I've updated so the `moved`, `allowDrag`, `allowMove` function now uses the `eventArgs` as first parameter. This enables to use view specific variables if needed.

```
<ul sortable="items.bind: images; moved($event); allow-drag.call($event); allow-move.call($event);">
</ul>
```
The `eventArgs`
`moved` args.fromIx, args.toIx 
`allowDrag` args.event, args.item
`allowMove` args.item

Also the default implementation for `allowDrag` is enhanced to

```
@bindable disallowedDragTagNames = ["INPUT", "SELECT", "TEXTAREA"];
  @bindable allowDrag = function(args) {
    if(this.disallowedDragTagNames.indexOf(args.event.target.tagName) !== -1) {
      return false;
    }
    if(args.event.target.isContentEditable) {
      return false;
    }
    return true;
  };
```
