### ISSUE TITLE
FR: Support the group property from sortable

### ISSUE THREAD

**Issue by PWKad** [oribella/aurelia-sortable#23]
The group property allows the developer to drop to a separate list.  This could be used in conjunction with the `oa-sortable` possibly.

**Comment by stoffeastrom** [comment]
@PWKad I might have had to little ☕️ this morning but I'm not sure I understand what you  mean by the `group` property. However I understand that it would be nice to handle moves between multiple sortables. In the past I had requirements also that it should be possible to visually "disable" other lists that you shouldn't be able to move to. This could be handle by setting a `typeFlag` on the `oa-sortable` and the `oa-sortable-item` which makes it possible t bit mask the opportunities when sorting.

Imaging you have a "bucket" list with all "food" items and then you have for example a drink list and a main   course list. You should always be able to move from the drink/main to food but when  moving from food you should only be able to move to drink if the item is of that type.

Is this what you mean or am I completely out in the blue here :)?

**Comment by PWKad** [comment]
In the sortable.js docs search for group, it is like you mentioned a way of letting the plugin know you can carry between lists and you can define behaviors for how the interaction occurs, such as moving,  cloning,  etc..

**Comment by PWKad** [comment]
I did not realize this plugin was not augmenting the sortable plugin from ruxaba
