### ISSUE TITLE
[Question] Sortable not working on table rows

### ISSUE THREAD

**Issue by AStoker** [oribella/aurelia-sortable#24]
I have a table who's rows are being constructed like this:
``` html
<tbody id="inputList" oa-sortable="items.bind: templateInputs">
    <tr repeat.for="input of templateInputs" oa-sortable-item="item.bind: input">
        <td>
            <label class="cursor-pointer actionable-text" click.trigger="highlightElement(input)" for="${input.ID}" title="Highlight element in preview">${input.ID}</label>
        </td>
        <td>
            <input value.bind="input.Name" id="${input.ID}" />
        </td>
        <td class="list-actions">
            <button class="e-btn e-btn-micro" click.trigger="removeField(input)">
                <div class="icon-container">
                    <inline-svg svg="resources/images/svg/X"></inline-svg>
                </div>
                <span>Delete</span>
            </button>
        </td>
    </tr>
</tbody>
``` 

I followed the instructions in the readme to get the sortable plugin configured, but I'm unable to sort the items (there doesn't appear to be any interaction working, as if the plugin isn't even hooked up).  
Am I missing something very elementary here?

**Comment by stoffeastrom** [comment]
Could it be [this](https://github.com/oribella/aurelia-sortable#default-disalloweddragtagnamesinput-select-textarea---element-tags-that-disallows-start-dragging)? That's the only thing I can think of spontaneously...

**Comment by stoffeastrom** [comment]
So the default `allowDrag` wont allow it? You could test it by binding a `allowDrag` function that returns true

**Comment by AStoker** [comment]
I was going off of the docs to try and get a minimal dragging setup. So literally all I did was bring in the library, add it as a plugin in the `main.js`, and then add those bindings to the table rows I showed above. 
I've set things up similar to what was done here (https://github.com/oribella/aurelia-sortable/issues/16#issuecomment-263092048)... Could be related.

**Comment by stoffeastrom** [comment]
Yes but if you are trying to move it from for example input it will not be allowed since you would want to enter something there.. according to the `allowDrag` default binding...

Did you try to change it?

**Comment by AStoker** [comment]
I added a function 
```
this.allowDrag = ()=> {
            console.log('here');
            return true;
        }
```
```
 <tbody id="inputList" oa-sortable="items.bind: templateInputs, allowDrag.bind: allowDrag">
```
But no joy. Is that what you were saying?

**Comment by stoffeastrom** [comment]
`allow-drag.bind: allowDrag`?

**Comment by AStoker** [comment]
Negatory ghost rider. Didn't work. I'm pressed to believe that it's not even hooking up correctly... I'll have to make a skeleton project and try and reproduce the error, then I can show you it (can't share too much production code right now).

**Comment by stoffeastrom** [comment]
I understand no problem. Hopefully it shouldn't be any problem but as you say it's easier to have a repro.

I'm wanting to have a fast possibility to gist but haven't had the time to look into it

**Comment by stoffeastrom** [comment]
I just thought of another thing. Make sure you don't 'kill' the event somewhere.. since the event listeners are on the `document`.

**Comment by AStoker** [comment]
There's no immediate function that should be killing the event... But it's possible there's one farther up the tree...

**Comment by fracz** [comment]
I can confirm the plugin does not work with `tbody>tr` structure. However, I was [unable to create gist with the example](https://github.com/oribella/aurelia-sortable/issues/27).

**Comment by stoffeastrom** [comment]
@fracz are you seeing the same behaviour as here? Any errors?

I agree we need to get a gist working

**Comment by fracz** [comment]
The same behaviour, i.e. no interaction with the rows at all. No errors in console.

**Comment by stoffeastrom** [comment]
I've managed to create a simple gist that actually throws an error saying

```javascript
Uncaught TypeError: Cannot read property 'oa-sortable-item' of undefined
    at Sortable.getItemViewModel (sortable.js:159)
```
Don't know if it's related but there is indeed something going on here. I'm going to finish my conversion of the oribella code base to typescript and revisit this to see if it can be fixed.

One thing that I thought of was that we might need to reintroduce the possibility to add the `dragging` item in the bound array instead of cloning it and adding it to the body. Else it would try to add the `tr` in the body [here](https://github.com/oribella/aurelia-sortable/blob/master/src/drag.js#L11-L20) and I guess that will not work.

**Comment by stoffeastrom** [comment]
I have a [gist](https://gist.run/?id=2b0ea59ee6e51865cc9508d0cabfea11) that uses the new typescript `Oribella` code and as I suspected there was a bug in the old where the passed element was the `tbody` and not the actual `tr` element. However as I said above it's weird attaching a `tr` to the body so I think we need introduce some strategy for the drag element e.g if it should be attached to the body or be inline.

Does that make any sense? Thoughts?

@AStoker @fracz

**Comment by stoffeastrom** [comment]
The above gist actually now works in chrome at least :)

**Comment by stoffeastrom** [comment]
This is now working in the latest.
