### ISSUE TITLE
[Question] Using this plugin with an aurelia cli project

### ISSUE THREAD

**Issue by klaa12924** [oribella/aurelia-sortable#25]
Hi, I am having some trouble trying to use this plugin with an aurelia cli project. I guess I am doing something wrong but I am not really sure what.

I installed the plugin with npm install oribella-aurelia-sortable 
Add the following to aurelia.json in my project:
`{
    "name": "oribella-aurelia-sortable",
    "path": "../node_modules/oribella-aurelia-sortable/dist/amd",
    "main": "index"
}`

And in my main.ts file added the plugin
`.plugin('oribella-aurelia-sortable')`

When I try to run my project it give me the error:
          
![aurelia sortable error](https://cloud.githubusercontent.com/assets/13704848/21092137/ebb95f8a-c04a-11e6-8aa5-9a8be33fe109.PNG)

Probably I am doing something wrong, would appreciate some help.

**Comment by stoffeastrom** [comment]
I haven't used it myself. There is another [issue](https://github.com/oribella/aurelia-sortable/issues/16#issuecomment-263092048) that might help you. It would be nice to support this so please report back with your findings..

**Comment by klaa12924** [comment]
@stoffeastrom Thanks for the quick response, I tried some things listed in the issue you mentioned, but could not get it to work either. Still new too all of this.

**Comment by klaa12924** [comment]
This one can be closest, the solution is mentioned in #16
