### ISSUE TITLE
[Question] Is it possible to use this plugin with  nested oa-sortable 's?

### ISSUE THREAD

**Issue by klaa12924** [oribella/aurelia-sortable#26]
Hi,

I am trying to use this plugin with nested oa-sortable's, is that possible?

first: oa-sortable: model.templateGroups
repeat for: group of model.templateGroups
second: oa-sortable: group
repeat for: field of group.templateFields

````html
<div  oa-sortable="moved.call: groupMoved($event); items.bind: model.templateGroups;">
    <div repeat.for="group of model.templateGroups" oa-sortable-item="item.bind: group;">

          <div oa-sortable="moved.call: fieldMoved($event); items.bind: group.templateFields;">
                <ul repeat.for="field of group.templateFields" oa-sortable-item="item.bind: field;">
                    <li>${field.label} - ${field.order}</li>
                </ul>
          </div>
    </div>
</div>
````
I can drag and drop the "group" oa-sortable, but when I try to drag and drop the "field" within a group I get an error.
````error
Uncaught TypeError: 
Cannot read property 'viewModel' of undefined
at Sortable.getItemViewModel (vendor-bundle.js:27640)
````
Am I doing something wrong, or is this just not possible?

**Comment by stoffeastrom** [comment]
I don't think that's possible right now. What's your use case? Is it similar to what I'm describing [here](https://github.com/oribella/aurelia-sortable/issues/23#issuecomment-260893025)?

**Comment by stoffeastrom** [comment]
It could be possible depending on how you are handling the for example `allowMove`. I realise we need a way to easy setup and reproduce this kind of stuff!

**Comment by stoffeastrom** [comment]
@klaa12924 It's now possible to make a gist. Fork [this](https://gist.run/?id=52506d95d3d4a9194c30cfb1decfcbe0) and make a repro. I'm updating the oribella code base so it would be good to understand if I already solved the it or not

**Comment by klaa12924** [comment]
@stoffeastrom I will try to do this weekend when I have some time

**Comment by klaa12924** [comment]
My [Fork](https://gist.run/?id=7a20866288820fd6144fdc33e972e3d5&sha=8a92b388bfbef0706543ee9fc6aa83b6a22e3644)? 

Kinda not sure if I did this the correct way, hope I didn't screw up something.

![image](https://cloud.githubusercontent.com/assets/13704848/21984271/757eba4c-dbf5-11e6-84a6-343476dd39a3.png)

Maybe this plugin isn't designed have this kind of behaviour, but it was something I needed, but I fixed it another way.

**Comment by stoffeastrom** [comment]
Ok So I forked that and use the latest `oribella` code. Now it doesn't crash but it's only possible to move the group. I guess you want to either move the group or the list in the group.

**Comment by klaa12924** [comment]
Yes, that's true. The groups in should be sortable and each individual list in each group should be sortable only in the group it's originaly in.

**Comment by stoffeastrom** [comment]
I have a [gist](https://gist.run/?id=e9a29428b70eb4afc9a0cc247a9dd000) where it seems to work quite good. The problem was that we didn't take care of getting the closest `oa-sortable` and make sure to remove the other `oa-sortable` when we found the closest one. So after updating `allowDrag`

```javascript
  @bindable allowDrag = args => {
    const target = args.event.target;
    const closest = this.closest(target, '[oa-sortable]');
    if(closest !== this.element) { // Make sure your inside the closest `oa-sortable`
      return false;
    }
    if (this.disallowedDragTagNames.indexOf(target.tagName) !== -1) {
      return false;
    }
    if (args.event.target.isContentEditable) {
      return false;
    }
    return true;
  };
```
and for the `down`

```javascript
down(e, data, element) {
    if (this.allowDrag({ event: e, item: this.getItemViewModel(element).item })) {
      e.preventDefault();
      return true; // Remove other gestures (might change this to not remove others since you could have advanced interaction scenario
    }
    return false; // Remove myself
  }
```

**Comment by klaa12924** [comment]
@stoffeastrom oh nice! That seems to work perfectly.
A nice extra feature to this plugin would be if you now could drag one item from one group to another. I actually don't need it at this point, but the great plugin would benefit from it when it could :)

Thanks for this great plugin!

**Comment by stoffeastrom** [comment]
@klaa12924 I've been working on converting the plugin to typescript and using the new `Oribella` codebase that also is converted to typescript. It was not that hard to enable moving between groups. I've a [demo](https://dist-ybvsagrevz.now.sh/) I'm working on to show case this. What do you think?

**Comment by klaa12924** [comment]
@stoffeastrom man that looks really good, the disabled drop things and even or odd is working perfectly.
I tested your demo with mousepad and touchscreen, should it also be working with touch?

**Comment by stoffeastrom** [comment]
I only tested it quickly on my iPhone but yes it should work on touch. Haven't tweaked it for windows hybrid devices though

**Comment by stoffeastrom** [comment]
@klaa12924 What do you mean by mousepad and touchscreen? Can you explain more what you are using :)?

**Comment by klaa12924** [comment]
I meant to say that mouse events works perfect, but the touch events on my laptop screen doesn't, Windows 10 and edge.

**Comment by stoffeastrom** [comment]
Ok, Yes I haven't tweaked it for hybid devices yet. Need to add correct css `touch-action` on the `li` and `touch-action: none;` on the `handle`. Then we should DOM Events fired from Edge :). Since this is how Microsoft decided to implemented the only way to make sure is that the consumer sets the correct css `touch-action`. Would be cool if you could test this out if you have a chance? The easiest would be to just add `touch-action:none;` on the `lui-icon--handle`.

So just to re-cap, if we don't get any DOM events nothing will work. To enable this for IE11+ on hybrid devices we need to set the correct css property `touch-action`. See [here](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) for more details. Excerpt

>By default, panning (scrolling) and pinching gestures are handled exclusively by the browser. An application using Pointer_events will receive a pointercancel event when the browser starts handling a touch gesture. By explicitly specifying which gestures should be handled by the browser, an application can supply its own behavior in pointermove and pointerup listeners for the remaining gestures. Applications using Touch_events disable the browser handling of gestures by calling preventDefault(), but should also use touch-action to ensure the browser knows the intent of the application before any event listeners have been invoked.

**Comment by stoffeastrom** [comment]
💥
