### ISSUE TITLE
Create a runnable sample gist with this plugin

### ISSUE THREAD

**Issue by fracz** [oribella/aurelia-sortable#27]
Creating a runnable example with any aurelia plugin without preconfigured `config.js` is really painful. If there was a sample runnable gist with the aurelia-sortable provided it would be simpler to create bug examples for issues.

See how for example [aurelia materialize does it](https://gist.run/?id=e8eed34e8bba17f5213535bcdd004a9e).

**Comment by stoffeastrom** [comment]
What about [this](https://gist.run/?id=e9587b5ac30e6650edd3b9404a700882)?. The `oribella` libs are not bundled but loaded via rawgit with es6 so it's a bit slow at the moment.

Thoughts?

**Comment by stoffeastrom** [comment]
Updated it to use `unpkg` so should be fine to start using some gists. I'm converting the oribella code base to typescript so might be worth to try out systemjs and typescript in the gists later on but closing this for now
