### ISSUE TITLE
Invalid position of dragged item

### ISSUE THREAD

**Issue by fracz** [oribella/aurelia-sortable#28]
In my app I have an issue that I cannot reproduce on your demo. The position of the dragged element in the sortable is ok only if the window is not scrolled. The farest I scroll the window, the worse the position of the element being dragged is (it is positioned above the mouse pointer). See the animation:

![animation](https://cloud.githubusercontent.com/assets/3918865/21760599/9aa6017a-d64d-11e6-8882-a6045d248c98.gif)

This is when using the minimal plugin code (i.e. only items bindings). I use bootstrap and I'm dragging `col-xs-12` elements inside a `row`.

Do you have any idea what might be the cause of such behavior?

**Comment by stoffeastrom** [comment]
It seems like you don't have bound the correct scrolling element? E.g it can't calculate the correct positions since it does'nt got the correct scrolling element to work with. 

Does the [readme](https://github.com/oribella/aurelia-sortable#default-scrollsortable) help you?

**Comment by fracz** [comment]
Adding the `scroll: document` helps, indded. I thought the `document` is the default. Thank you!
