### ISSUE TITLE
Allow to specify drag handle

### ISSUE THREAD

**Issue by fracz** [oribella/aurelia-sortable#29]
It would be nice to be able to specify a drag handle (like in [jQuery UI](http://api.jqueryui.com/sortable/#option-handle)), so the element can be dragged only by specific child element. For example:

```
oa-sortable="drag-handle.bind: '.drag-handle'
```

Currently, it can be achieved with:

```
oa-sortable="allow-drag.call: isDragHandle($event);"
```

```
isDragHandle(data) {
  return $(data.event.target).is('.drag-handle') || $(data.event.target).parents('.drag-handle').length > 0;
}
```

**Comment by stoffeastrom** [comment]
Currently it handle [tags](https://github.com/oribella/aurelia-sortable/blob/master/src/sortable.js#L24-L33) only. I guess it would be simple to add something like

`disallowedSelectorNames` that would use `matchesSelector`

thoughts?

**Comment by fracz** [comment]
Yeah, I know there is a blacklist, but whitelist would be also nice (i.e. `allowedSelectorNames`).

This is not a *must-have*, just a suggestion.

**Comment by stoffeastrom** [comment]
You can now use

```
<div oa-sortable="allow-drag-selector.bind: '.handle'">
```
