### ISSUE TITLE
Drag without position swap can leave dragged item out of position

### ISSUE THREAD

**Issue by gavinaiken** [oribella/aurelia-sortable#3]
If you start a drag on a sortable item but do not move it far enough for it to switch position with another item, then let go, the item will be left out of position. This seems to be because the item has a `style` attribute with `left` and `top` settings left applied. 

e.g. see this screen shot of the flickr demo after an aborted drag:

![screen shot 2015-08-17 at 16 49 43](https://cloud.githubusercontent.com/assets/932263/9318351/20712928-4500-11e5-8860-98ed0e3b12b6.png)

**Comment by gavinaiken** [comment]
Presume this is related to this commit: https://github.com/oribella/aurelia-sortable/commit/adef95970c0d554d06e1e99d869c8cf14465b520 - maybe adding `left` and `top` to the saved style will fix it?

https://github.com/oribella/aurelia-sortable/commit/adef95970c0d554d06e1e99d869c8cf14465b520#diff-cb96d169580ab6483aca2856d7371c5cR78

**Comment by stoffeastrom** [comment]
Yes. There was another problem if I removed the style completely since you could have a style.bind on the sortable item. Your theory sounds correct will look into this

**Comment by gavinaiken** [comment]
Thanks for the quick fix, worked for me! :)

**Comment by stoffeastrom** [comment]
Np, thanks for reporting! :)
