### ISSUE TITLE
It does not work with aurelia-bundler

### ISSUE THREAD

**Issue by fracz** [oribella/aurelia-sortable#30]
When using [`aurelia-bundler`](https://github.com/aurelia/bundler), the only file that is bundled from this plugin is the `index.js`. AFAIU, this is because the `index.js` does not export all classes that the plugin use. [Related issue](https://github.com/aurelia/bundler/issues/30)

**Comment by stoffeastrom** [comment]
See [this](https://github.com/oribella/aurelia-sortable/issues/16#issuecomment-268549081)

**Comment by fracz** [comment]
Aurelia CLI != aurelia-bundler. I use aurelia-bundler with JSPM and TS.

According to [this comment](https://github.com/aurelia/bundler/issues/30#issuecomment-152883574) and a sample from [aurelia-templating](https://github.com/aurelia/templating-resources/blob/master/src/aurelia-templating-resources.js), a plugin should export all of its dependencies in the main file so bundler knows what to bundle.

**Comment by stoffeastrom** [comment]
That doesn't seem right to me. The whole point is that it should get loaded up front. That's just a work around for the bundler. What I think you need is to define the bundler vendor packages correct. I remember having that kind of discussion let me see if I can find it...

**Comment by stoffeastrom** [comment]
Oh it was en the same thread as [above](https://github.com/aurelia/bundler/issues/30#issuecomment-153382016)

**Comment by stoffeastrom** [comment]
This should be much easier since there only is 2 dependencies in the latest e.g

oribella-framework
oribella

Configure according to the CLI

It seems like there was something coming for the bundle to make it easier but if not maybe we should do that trick you mentioned above

**Comment by gronostajo** [comment]
Bundling `oribella` with v0.11.0 indeed helps, but `oribella-aurelia-sortable` itself doesn't bundle properly. `oribella-aurelia-sortable.js` is bundled, but other files aren't:

- `auto-scroll.js`
- `optional-parent.js`
- `sortable.js`
- `utils.js`

**Comment by gavinaiken** [comment]
I tested the latest, with jspm and the aurelia-bundler, and had difficulty getting it to load. It seemed to have a dependency on `tslib.js`, but that should be a devDependency, not a dependency according to the package.json? Is there a problem with the build process?

**Comment by stoffeastrom** [comment]
Weird, it's stated as a [dev dependency}(https://github.com/oribella/aurelia-sortable/blob/master/package.json#L67)

**Comment by stoffeastrom** [comment]
Oh, it should be a `dependencies` and not a `devDependency` since it is used the generated files

**Comment by gavinaiken** [comment]
If it is required to run the generated files, it should be a `dependency`, `devDependencies` should only be required for testing / development. But the compiled files in `dist/commonjs` definitely require `tslib`

**Comment by stoffeastrom** [comment]
Yes, I added it to get less bloat but forget to add it in the `dependency`. Could you try to `npm install tslib` and see if it works for you?

**Comment by stoffeastrom** [comment]
eerh I mean `jspm install....`

**Comment by stoffeastrom** [comment]
Actually I guess you have to use `npm install tslib` :)

**Comment by stoffeastrom** [comment]
https://github.com/oribella/aurelia-sortable/issues/30#issuecomment-283335017

Yes that's correct you have to add those for the bundler

**Comment by stoffeastrom** [comment]
We might have to do that trick to import / export them so it picks it up automatically..

**Comment by gavinaiken** [comment]
Adding `tslib` with jspm works. I had to also add several aurelia packages as top-level dependencies. I think that would not be necessary if they were added to the jspm dependencies in package.json of your distributed module. Doing a bit more testing to try to confirm that...

**Comment by gavinaiken** [comment]
There seems to be something wrong with the way the compiled files are `require`ing the dependencies. I can get jspm to install everything along with aurelia-sortable using this command:

```
jspm install npm:oribella-aurelia-sortable -o '{"dependencies": {"oribella": "^0.8.0", "oribella-framework": "^0.10.0", "aurelia-pal": "^1.3.0", "aurelia-templating": "^1.3.0", "tslib": "^1.6.0" }}'
```

but the dependencies fail to load in the browser unless they are installed separately as top level dependencies like this:

```
jspm install aurelia-pal
jspm install aurelia-templating
jspm install npm:tslib
```

**Comment by stoffeastrom** [comment]
Yes, I see that those are missed for the `jspm`. Would be great if you could verify so it works for you guys using `jspm`.

**Comment by stoffeastrom** [comment]
Also, I'm happy to take a PR that makes life easier for you guys using the bundler. Or if you could post exactly what need to be added so it picks it up automatically.

**Comment by gavinaiken** [comment]
Earlier comment was wrong. If I specify `aurelia-pal` and `aurelia-templating` as dependencies in the `jspm` command, then they do NOT also need to be installed as top level dependencies. But `tslib` does... not sure why!

i.e. this works for me with jspm:

```
jspm install npm:oribella-aurelia-sortable -o '{"dependencies": {"oribella": "^0.8.0", "oribella-framework": "^0.10.0", "aurelia-pal": "^1.3.0", "aurelia-templating": "^1.3.0", "tslib": "^1.6.0" }}'
jspm install npm:tslib
```

Not sure what changes would be required to fix that, otherwise I would do a PR. Still testing things...

**Comment by gavinaiken** [comment]
`0.11.1` resolves the problem with jspm and `aurelia-pal` and `aurelia-templating`. But it is still necessary to also install `tslib` to make it work. i.e. I was able to do this:

**Comment by stoffeastrom** [comment]
Oh sorry, I totally missed `tslib`... I will add it

**Comment by gavinaiken** [comment]
I don't think it will work though... I tried that with the jspm `-o` override as in my comment above, and it doesn't work. I don't understand exactly why though, something to do with how systemjs resolves the dependencies.

**Comment by stoffeastrom** [comment]
Hmm, ok.. Let me know if you find out how this should be done

**Comment by gavinaiken** [comment]
Oh I think I might know why, I expect `tslib` is in `global` format, according to jspm's conventions. I think there is a way to work around that. Will research tomorrow and let you know.

**Comment by stoffeastrom** [comment]
Great! Let's move this to separate issue

**Comment by stoffeastrom** [comment]
@gronostajo [this](https://github.com/oribella/aurelia-sortable/issues/30#issuecomment-283335017) is hopefully fixed in `0.11.2`. Would be great if you can test it and report back

**Comment by stoffeastrom** [comment]
@gavinaiken if you are using the bundler I'd appreciate if you tested this also :)

**Comment by gavinaiken** [comment]
Seems to work great to me in the latest version `0.11.2`. My aurelia-bundler config just lists `'oribella-aurelia-sortable'` in the `includes` section, and I see that the resulting bundle contains:

```
      "npm:oribella-aurelia-sortable@0.11.2.js",
      "npm:oribella-aurelia-sortable@0.11.2/auto-scroll.js",
      "npm:oribella-aurelia-sortable@0.11.2/optional-parent.js",
      "npm:oribella-aurelia-sortable@0.11.2/oribella-aurelia-sortable.js",
      "npm:oribella-aurelia-sortable@0.11.2/sortable.js",
      "npm:oribella-aurelia-sortable@0.11.2/utils.js",
      "npm:oribella-framework@0.10.2.js",
      "npm:oribella-framework@0.10.2/engine.js",
      "npm:oribella-framework@0.10.2/flow.js",
      "npm:oribella-framework@0.10.2/flows/mouse.js",
      "npm:oribella-framework@0.10.2/flows/ms-pointer.js",
      "npm:oribella-framework@0.10.2/flows/pointer.js",
      "npm:oribella-framework@0.10.2/flows/touch.js",
      "npm:oribella-framework@0.10.2/gesture.js",
      "npm:oribella-framework@0.10.2/listener-handle.js",
      "npm:oribella-framework@0.10.2/listener.js",
      "npm:oribella-framework@0.10.2/oribella-api.js",
      "npm:oribella-framework@0.10.2/oribella-framework.js",
      "npm:oribella-framework@0.10.2/point.js",
      "npm:oribella-framework@0.10.2/registry.js",
      "npm:oribella-framework@0.10.2/utils.js",
      "npm:oribella@0.8.2.js",
      "npm:oribella@0.8.2/doubletap.js",
      "npm:oribella@0.8.2/longtap-swipe.js",
      "npm:oribella@0.8.2/longtap.js",
      "npm:oribella@0.8.2/oribella.js",
      "npm:oribella@0.8.2/pinch.js",
      "npm:oribella@0.8.2/rotate.js",
      "npm:oribella@0.8.2/swipe.js",
      "npm:oribella@0.8.2/tap.js",
```

**Comment by gavinaiken** [comment]
I am using aurelia-bundler version `0.5.0` in case that helps anyone else

**Comment by stoffeastrom** [comment]
I'm closing this. Please re-open if it doesn't work

**Comment by fracz** [comment]
Works for me, too. Thank you!

**Comment by gronostajo** [comment]
Same here, works perfectly. Thanks!
