### ISSUE TITLE
Question: is there still an option to leave a blank space where the dragged item will go?

### ISSUE THREAD

**Issue by gavinaiken** [oribella/aurelia-sortable#32]
In the older versions of the library, the dragged item would leave a "hole" in the list where it was initially, and that hole would move as you dragged the item around, indicating where it will snap to once released from the drag.

In the latest version it appears that the dragged item is cloned so you see it both being dragged, and in the position it will land.

Is there any option in the latest version to make it act like the older version? I thought it was more easy to see what was happening, especially if the thing you are dragging around is quite large.

**Comment by stoffeastrom** [comment]
That must be an really old version :). As I recall we added the clone to be able to handle one of your scenarios with the whole page scrolling? What do you want to control?

**Comment by gavinaiken** [comment]
Yes, I'm still using 0.6.0 in production.

I don't think the clone was added for me, although I am guilty as charged with the whole page scrolling feature.

**Comment by gavinaiken** [comment]
The thing I want to control is what is shown in the space that the item being dragged will land in. In the new version, you see 2 copies of the item being dragged - I want to only see 1 (moving around as I drag), and for there to simply be a gap in the list in the current snap-to drag landing position.

**Comment by gavinaiken** [comment]
The reason I say that I don't think the clone was added for me is that 0.6.0 works perfectly for me, and it doesn't clone ;)

**Comment by stoffeastrom** [comment]
Could you use `oa-drag` class that is set? Maybe put a `opacity`on it?

**Comment by stoffeastrom** [comment]
Oh that wont work..but if we set a class on the item in the list...

**Comment by gavinaiken** [comment]
Yeah, the `oa-drag` class is on the item being dragged I think? I want to control the appearance of the item in the list. `oa-drag-placeholder` or something...

**Comment by gavinaiken** [comment]
There used to be a `placeholder-class` option.

**Comment by gavinaiken** [comment]
I think this was the issue raised which required the change to the placeholder/clone: https://github.com/oribella/aurelia-sortable/issues/14

**Comment by stoffeastrom** [comment]
It seems i missed to add the `oa-drag` also. I will add that to the item being dragged and not the clone. We can add a `oa-clone` on that one if we need

**Comment by stoffeastrom** [comment]
`0.11.1` now have the `oa-sorting`. This class will be set on the current item being sorted. So you can add

```
.oa-sorting {
  opacity: 0.3;
}
```
for example

**Comment by gavinaiken** [comment]
Great! Will test shortly.

**Comment by gavinaiken** [comment]
That works very nicely! Thank you.

**Comment by stoffeastrom** [comment]
Great! Thanks for pointing out that "missing" feature ;)
