### ISSUE TITLE
Latest version seems to break the moved callback functionality

### ISSUE THREAD

**Issue by gavinaiken** [oribella/aurelia-sortable#34]
We rely on the `moved` callback to save prefs after things have been re-ordered, with config like this:

`oa-sortable="items.bind: config.widgets; moved.call:moved($event);"`

This worked in `0.6.0` but `moved` is not being called in `0.11.2`. Looking at the code I see it is still declared as a bindable but doesn't seem to ever be called.

**Comment by stoffeastrom** [comment]
No, problem is that it's now possible to move between sortables. So there needs to be a breaking change. Don't know would be the best api. Why do you need it?

**Comment by stoffeastrom** [comment]
So you can't save the array? Or how do you save the preferences

**Comment by gavinaiken** [comment]
Yes, I use it to know when a change has been made, so I can save the updated order of the array, which can then be restored if the user leaves that part of the app and returns later.

**Comment by stoffeastrom** [comment]
Do you want a callback that it's finished or actually moved with from indices etz?

**Comment by gavinaiken** [comment]
Only need a callback that it's finished, then I can inspect the array to see what order things are in.

**Comment by stoffeastrom** [comment]
Because adding a callback when it's moved is easy but a bit more complicated if we should handle which from array and index and to array and to index

**Comment by stoffeastrom** [comment]
So lets trigger the `moved` with empty args to begin with

**Comment by gavinaiken** [comment]
That works great, I don't use the `event` arg in my existing code

**Comment by stoffeastrom** [comment]
Or maybe we should change it to `stop` which is always called when the user releases the flow

**Comment by stoffeastrom** [comment]
and if `moved` is needed we can send in from list to list etz

**Comment by gavinaiken** [comment]
If you don't know whether anything changed places or not, then `stop` seems to make more sense

**Comment by stoffeastrom** [comment]
Exactly what I though, I already have `stop` callback from `oribella` code so it will be 

```
@bindable onStop(): () => void = () => {};

**Comment by gavinaiken** [comment]
Thanks, works great.
