### ISSUE TITLE
Doesn't work without bundling

### ISSUE THREAD

**Issue by gronostajo** [oribella/aurelia-sortable#35]
It's a follow-up to #30 I suppose.

My app now works perfectly when it's bundled, but without bundling I'm getting this error:

> Unhandled rejection (SystemJS) Unable to dynamically transpile ES module as SystemJS.transpiler set to false.
> 	[...]
> 	Error loading http://localhost/jspm_packages/npm/tslib@1.6.0.js as "tslib" from http://localhost/jspm_packages/npm/oribella-aurelia-sortable@0.11.3/auto-scroll.js

Reverting to v0.8.0 fixes this.

It indeed seems that `tslib@1.6.0.js` uses modern JS and should be transpiled:

```
export * from "npm:tslib@1.6.0/tslib.js";
export {default} from "npm:tslib@1.6.0/tslib.js";
```

However I shouldn't be supposed to transpile dependencies myself.

Strictly speaking, it's the `auto-scroll.js` file which is the culprit, it uses `__decorate` method from `tslib`. I've checked how [aurelia-validation](https://github.com/aurelia/validation) (which is written in TS too) deals with this issue and it seems that it has the `__decorate` method [embedded](https://github.com/aurelia/validation/blob/master/dist/es2015/validation-errors-custom-attribute.js#L1) rather than imported from `tslib`.

**Comment by stoffeastrom** [comment]
https://github.com/Microsoft/tslib/issues/26

**Comment by stoffeastrom** [comment]
Looks like there is PR

**Comment by stoffeastrom** [comment]
@gronostajo Looks like this should work now according to the above issue? Can we close this issue?

**Comment by gronostajo** [comment]
Yes, it seems to be fixed. Thank you for finding that issue.
