### ISSUE TITLE
Relative path issue

### ISSUE THREAD

**Issue by etiennemorin** [oribella/aurelia-sortable#39]
It seems to me that there might be some root path references instead of relative path references within oribella-aurelia-sortable.  Is this possible?

I'm getting file not found exceptions when I run `au run --watch`

`Tracing oribella-aurelia-sortable...
File not found or not accessible: c:/projectdirectory/src/oribella.js. Requested by c:\projectdirectory\node_modules\oribella-aurelia-sortable\dist\amd\oribella-aurelia-sortable.js
File not found or not accessible: c:/projectdirectory/src/tslib.js. Requested by c:\projectdirectory\node_modules\oribella-aurelia-sortable\dist\amd\oribella-aurelia-sortable.js
File not found or not accessible: c:/projectdirectory/src/oribella-framework.js. Requested by c:\projectdirectory\node_modules\oribella-aurelia-sortable\dist\amd\oribella-aurelia-sortable.js
File not found or not accessible: c:/projectdirectory/src/oribella.js. Requested by c:\projectdirectory\node_modules\oribella-aurelia-sortable\dist\amd\oribella-aurelia-sortable.js
File not found or not accessible: c:/projectdirectory/src/tslib.js. Requested by c:\projectdirectory\node_modules\oribella-aurelia-sortable\dist\amd\oribella-aurelia-sortable.js
File not found or not accessible: c:/projectdirectory/src/oribella-framework.js. Requested by c:\projectdirectory\node_modules\oribella-aurelia-sortable\dist\amd\oribella-aurelia-sortable.js
Tracing oribella...
Tracing tslib...
Tracing oribella-framework...`

I ran

`au install oribella-aurelia-sortable`

which installed in package.json

`"oribella-aurelia-sortable": "^0.11.3"`

and in aurelia.json

            {
                "name": "oribella-aurelia-sortable",
                "main": "oribella-aurelia-sortable",
                "path": "../node_modules/oribella-aurelia-sortable/dist/amd",
                "resources": []
            }

I'm running an ASP.NET Core application with some unconventional settings, could that be the issue (aurelia.json)?

 "paths": {
    "root": "src",
    "resources": "resources",
    "elements": "resources/elements",
    "attributes": "resources/attributes",
    "valueConverters": "resources/value-converters",
    "bindingBehaviors": "resources/binding-behaviors"
  },
  "build": {
    "targets": [
      {
        "id": "aspnetcore",
        "displayName": "ASP.NET Core",
        "output": "wwwroot/scripts",
        "index": "wwwroot/index.html",
        "baseDir": "./wwwroot",
        "baseUrl": "scripts"
      }
    ],

Do you have any suggestions?

**Comment by etiennemorin** [comment]
It turns out I needed to add all the dependencies in manually in aurelia.json 

`{
                        "name": "tslib",
                        "main": "tslib",
                        "path": "../node_modules/tslib",
                        "resources": []
                    },
                    {
                        "name": "oribella",
                        "main": "oribella",
                        "path": "../node_modules/oribella/dist/amd",
                        "resources": []
                    },
                    {
                        "name": "oribella-framework",
                        "main": "oribella-framework",
                        "path": "../node_modules/oribella-framework/dist/amd",
                        "resources": []
                    },
                    {
                        "name": "oribella-aurelia-sortable",
                        "main": "oribella-aurelia-sortable",
                        "path": "../node_modules/oribella-aurelia-sortable/dist/amd",
                        "resources": []
                    }`

**Comment by stoffeastrom** [comment]
@etiennemorin Glad it worked yout for you!
