### ISSUE TITLE
Latest aurelia release breaks aurelia-sortable

### ISSUE THREAD

**Issue by gavinaiken** [oribella/aurelia-sortable#4]
Just opening an issue to see if you know about the latest aurelia release http://blog.durandal.io/2015/10/13/aurelia-mid-october-2015-releases-performance-and-portable-javascript/ and if you're planning an update to sortable to handle the breaking changes?

**Comment by stoffeastrom** [comment]
Yes. New **Patch** release. Let me know if it's working for you.

**Comment by gavinaiken** [comment]
Awesome, will test in the morning and let you know. Thanks!

**Comment by gavinaiken** [comment]
Yes, works perfectly for me. Thanks!

**Comment by stoffeastrom** [comment]
Great!
