### ISSUE TITLE
[Question] How to retrieve the position within a sortable list?

### ISSUE THREAD

**Issue by PhilipTKC** [oribella/aurelia-sortable#41]
As the title says, How do you retrieve the 'old' and 'new' index position?

eg.

Moving *[0] Item 1* into *Position [3]* would yield the results

Old Position: [0]
New Position: [3]

* [0] Column 1
    * [0] Item 1
    * [1] Item 2
    * [2] Item 3
    * [3] Item 4

**Comment by stoffeastrom** [comment]
Hi @PhilipTKC,

In an earlier version you got that in the `moved` callback. However this was removed when introducing multiple sortable lists for simplicity. May I ask why you need it? The plugin operates on list references and actually move them in the arrays you provide.

**Comment by PhilipTKC** [comment]
Hi @stoffeastrom 

I'm still quite new to this but I wanted the index position to update the positions in my database. I have the following method that I 'was' using with Knockout before I started to convert my application to Aurelia. I hope this makes sense.

[Gist](https://gist.github.com/PhilipTKC/96e93c447db7b6ad5d6f1998bb1f8939)

**Comment by stoffeastrom** [comment]
That makes sense. We could re-introduce the `moved` callback but I'm not sure about the api. It needs to support moving between multiple lists. 

```shell
this.moved({
  from: {
    list: fromList,
    index: fromIndex
  },
  to: {
    list: toList,
    index: toIindex
  }
});
```

@PhilipTKC what do you think?

**Comment by PhilipTKC** [comment]
Hi @stoffeastrom 

Thanks for the feedback. It gave me an idea just to loop through the array. I ended up using the index of the array to set the new TaskWeight and the column id if it's been moved between a column.

![col](https://user-images.githubusercontent.com/17052464/28205762-843b61b0-68d7-11e7-95d4-bb495c9b8210.PNG)

            var serialized = JsonConvert.SerializeObject(project.Project);
            var columns = JsonConvert.DeserializeObject<List<Columns>>(serialized);
            foreach (var col in columns)
            {
                var i = 0;
                foreach (var t in col.ProjectTask)
                {
                    var task = _context.Tasks.AsNoTracking().SingleOrDefault(x => x.TaskId == t.TaskId);
                    task.TaskWeight = i;
                    task.ColumnId = col.ColumnId;
                    i++;
                    _context.Update(task);
                }
            }

I guess this can be closed. Thanks again :)

**Comment by stoffeastrom** [comment]
No problem!

Yes, `onStop` is always called to ensure you can clean up things but it doesn't say if something was actually moved or not. If need we could easily provide something that says if it's valid move.

**Comment by PhilipTKC** [comment]
> If need we could easily provide something that says if it's valid move.

That would be wonderful :)

**Comment by stoffeastrom** [comment]
So just to be sure. Should we add the `moved` callback again but with no arguments. This will be called if it's  a valid move and you can bind to it. I'm not sure what  you are using now since there are no public callbacks. Are you overriding the `onStop`?

**Comment by PhilipTKC** [comment]
I am currently using on-stop.call: onStop() and I am simply doing a post request with my updated view-model.

**Comment by stoffeastrom** [comment]
@PhilipTKC I'm leaning towards [this](https://github.com/oribella/aurelia-sortable/compare/master...iss41). So keep the `onStop` and get a `move` interface where you get

```
export enum MoveFlag {
  Invalid = 0,
  Valid = 1,
  ValidNewList = 2
}

export interface Move {
  flag: MoveFlag;
  fromItems: any[];
  fromIndex: number;
  toItems: any[];
  toIndex: number;
}
```
So you can guard it for example

```
onStop(move: Move) {
  if (move.flag === MoveFlag.Invalid) {
    return;
  }
}
```
what do you think?

**Comment by PhilipTKC** [comment]
That looks excellent.

**Comment by stoffeastrom** [comment]
@PhilipTKC you can try this out with using the `next` tag e.g

```shell
npm i oribella-aurelia-sortable@next
```
Let me know how it works

**Comment by PhilipTKC** [comment]
Can do, I've been testing it for a little while now but I've encountered an issue with "FromIndex"

items = [1, 2, 3, 4, 5, 6, 7];

Moving "1" after "7" seems to register the "FromIndex" as "6" rather than "0".

I've provided some images below. 

Step 1: ![1](https://user-images.githubusercontent.com/17052464/28294996-b4cd7af2-6bb1-11e7-849d-34bb6d0da8a8.PNG)

![2](https://user-images.githubusercontent.com/17052464/28294997-b4ce035a-6bb1-11e7-85ae-e063a0b600fb.PNG)

Step 2: ![3](https://user-images.githubusercontent.com/17052464/28294998-b4cecc4a-6bb1-11e7-9e97-e3e6105c0683.PNG)

![4](https://user-images.githubusercontent.com/17052464/28294999-b4d0d8aa-6bb1-11e7-9bf5-c9e7c23919de.PNG)

**Comment by stoffeastrom** [comment]
It's the `fromIndex` so it's where it's dragged from. That makes most sense right? If you need the original I think you have to get that yourself from a shallow copy of the array. If you store object references it would be quite easy to get that if we also pass the `item` being moved. Should we add the `item` in the interface or what do you think?

**Comment by PhilipTKC** [comment]
Yep, That makes complete sense. I was just making sure :).

> Should we add the item in the interface or what do you think?

That would be nice, I was currently getting it via allow-drag as a work around. :rofl:

**Comment by stoffeastrom** [comment]
You can try it out again :) with the `next` tag

**Comment by PhilipTKC** [comment]
Awesome, Works like a charm. 👍

Thanks @stoffeastrom 🍺
