### ISSUE TITLE
No getting started guidance

### ISSUE THREAD

**Issue by pbrickell** [oribella/aurelia-sortable#5]
Would like to explore this. Guessed installation command (jspm install github:oribella/aurelia-sortable). 

Do not know what require to use to get the sortable attribute. Can you make source for the demo available at least?

**Comment by stoffeastrom** [comment]
It's available in the `demo` branch. Haven't updated that for the latest though. I'm holding off a bit until theres an Aurelia beta. My hope is to be able to use the new App documentation part and get some nice documentation

**Comment by stoffeastrom** [comment]
@pbrickell i've updated the `README.md` with some getting started guidance
