### ISSUE TITLE
placeholder class is not added in aurelia 1.0.0-beta.1.

### ISSUE THREAD

**Issue by timfish** [oribella/aurelia-sortable#6]
Thanks for the great library!

I've been trying it out with the latest beta build and the placeholder class is not getting added to my sortable-item element. I'll see if I can get a simple example with this reproduced.

The Flickr example appears to be working fine on 0.17.0/0.18.0

**Comment by stoffeastrom** [comment]
Please do. I just ran the sample and it looks like it's adding `placeholder` to the `sortable-item`. I think the sample is running the latest release but I'll check that again

**Comment by timfish** [comment]
I worked it out. It wasn't immediately clear from `README.md` docs that I needed to add `${image.placeholderClass}` to the `sortable-item` class attribute. I then noticed the code example on the right hand side of the Flickr example. I'd assumed the class was added automagically.

**Comment by stoffeastrom** [comment]
Great! I will add a note in the `README.md`

**Comment by stoffeastrom** [comment]
Heads up. New version where you don't have to define the `placeholder` yourself anymore. Instead the dragging view-model item is cloned and a new `placeholderClass` binding is used
