### ISSUE TITLE
Long sortable without a scrollable area

### ISSUE THREAD

**Issue by gavinaiken** [oribella/aurelia-sortable#8]
If you use sortable without a containing scrollable `div`, dragging an item does not work if the whole page is scrolled.

To reproduce you need a long sortable list so that the whole browser window is scrollable. Scroll to the bottom of the page and try to drag a sortable item at the bottom of the list. It does not detect which item it has been dragged above because it does not offset for the scroll of the page correctly.

**Comment by gavinaiken** [comment]
Changing this line:

https://github.com/oribella/aurelia-sortable/blob/master/src/sortable.js#L229

to this:

```
        var x = e.clientX;
        var y = e.clientY;
```

seems to mainly fix the issue for me. At least it means that the position of the draggable object is relative to the viewport and then the `document.elementFromPoint` returns the correct item. Scrolling doesn't work though, if you drag to the edge of the screen nothing happens.

I also tested this change in the case where there is a scrollable container div and it seemed to work fine, nothing was broken, and of course the auto scrolling worked fine in that case with the correct binding in the sortable attribute.

**Comment by gavinaiken** [comment]
Seems like this line:

https://github.com/oribella/aurelia-sortable/blob/master/src/sortable.js#L58

should probably be something like this to get the document body, rather than the sortable element itself:

```
          this.scroll = this.element.ownerDocument.body;
```

although that isn't making the scrolling work. Testing some other things...

**Comment by gavinaiken** [comment]
Looks like changes would also be needed in the auto-scroll class. Hacking around I've got it working upwards, sort of (the dragging item jumps from under the mouse when I hit the top of the screen but otherwise it works), but not when dragging down to the bottom.

**Comment by stoffeastrom** [comment]
@gavinaiken you need to bind the correct `scroll` element else it will default to `sortable` element. Need to investigate

**Comment by stoffeastrom** [comment]
I'm trying to reproduce this but I can't. I tried removing the `overflow: auto` from the demo but it still works as expected..

@gavinaiken Is it possible to reproduce this in a plunker?

**Comment by gavinaiken** [comment]
Hmm have never made a plunker before. Just had a quick look but wasn't that obvious what I need to do, will take me a little while to figure it out I think, so I will work on it in the morning. I think in your demo page you have the `.page-host` set to absolute positioning and set to the same size as the viewport. If you set your scroll element to the document body you should be able to reproduce what I see, I think... but I will try to get a plunker setup tomorrow.

**Comment by stoffeastrom** [comment]
I will try that and see. So how are you binding `scroll`? to the document.body just `scroll.bind: 'body'`?

**Comment by gavinaiken** [comment]
Tried a couple of things, I set a class on my body and bound to that eg `scroll.bind: '.body'`, but I also changed the code as mentioned above, so that it defaults to the page body if you don't specify what to bind to.

https://github.com/oribella/aurelia-sortable/blob/master/src/sortable.js#L58

Before:

```
activate() {
    this.removeListener = oribella.on(this.element, "swipe", this);
    if(typeof this.scroll === "string") {
      this.scroll = this.closest(this.element, this.scroll);
    }
    if(!(this.scroll instanceof DOM.Element)) {
      this.scroll = this.element;
    }
    this.removeScroll = this.bindScroll(this.scroll, this.onScroll.bind(this));
  }
```

after:

```
activate() {
    this.removeListener = oribella.on(this.element, "swipe", this);
    if(typeof this.scroll === "string") {
      this.scroll = this.closest(this.element, this.scroll);
    }
    if(!(this.scroll instanceof DOM.Element)) {
      this.scroll = document.body;
    }
    this.removeScroll = this.bindScroll(this.scroll, this.onScroll.bind(this));
  }
```

**Comment by gavinaiken** [comment]
Can reproduce it by turning off `position: absolute` on your demo page (not exactly identical to my situation but the result looks identical - can still resort the items at the top of the list, but when you scroll to the bottom you can't):

![untitled](https://cloud.githubusercontent.com/assets/932263/12658549/99d98076-c601-11e5-86b4-ef74993d92e5.gif)

**Comment by stoffeastrom** [comment]
Ok, I've reproduced it also. Will do some investigation!

**Comment by stoffeastrom** [comment]
Hmm, but i'm not sure that is valid since we need to set the correct `scroll`

**Comment by stoffeastrom** [comment]
@gavinaiken The root cause seems to be that the scroll element doesn't have a correct height. This is needed else the plugin can't calculated the correct bounding rect which is needed to auto scroll and set x, y before trying to get the `elementFromPoint`.

Make sure to set the correct css for the `body`. Go into the console and log out `document.body.getBoundingClientRect()` that rect needs to represent the scrollable area.

It might be possible to detect this use case but I'm not sure yet.

**Comment by gavinaiken** [comment]
Using an absolute-positioned, 100% height/width wrapper div with `overflow: auto` seems to be a reasonable work-around, I've got that working now without needing any major changes to my html/css structure. It would be nice if the library automatically handled the case where the whole page is scrollable but having played around with some things myself that seems like it would require quite a few changes. So maybe just a note in the readme saying that scenario isn't supported would be best? I can do a pull request for the readme changes if you'd like?

**Comment by stoffeastrom** [comment]
That sounds reasonable! If it's possible to handle this case in a simple way we can add it but it needs some more thinking :).

PR welcome for the readme

**Comment by stoffeastrom** [comment]
Did you check if the `body` height is correct? Good to know if that's actually the problem. You should be able to make it work by setting something like

```css
html, body {
  position: relative;
  min-height: 100%;
}
```

**Comment by gavinaiken** [comment]
Tested that this morning, doesn't help. The main problem when not using a div which is set to be the same size as the view port seems to be that the `x, y` that you're getting from `getPoint` in `Sortable#update` is relative to the scroll container, not the viewport. If the scroll container is a normal relative-positioned div with content that is longer than the viewport, and the page is scrolled so that the bottom of the div is visible and the top of the div is off the top of the screen, the `y` value you get will be higher than the max `y` dimension of the viewport. e.g. if my viewport is only 1000px high but my scroll container div is 1500px high, i can get `y` vals from `getPoint` of up to 1500px. However then you feed that same `y` into `elementFromPoint(x, y)` which needs x and y to be relative to the viewport.

So as far as I understand the code, it will only work if you use a container div which has a height constrained to be 100% of the viewport, at least without changes. (One possible route to go in terms of code changes is the use of the event `e.clientY` which is in terms of the viewport, not the div, but that also requires a bunch of other changes to make it work.)

**Comment by stoffeastrom** [comment]
Need to investigate some more. Never stumbled on that kind of use case. But I think I undestand it better now. https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint this actually says *viewport* so your theory might be right :).

**Comment by stoffeastrom** [comment]
@gavinaiken to make sure I understand it correctly and have a valid test case would it be possible to for you to add repo where this is setup for me?

**Comment by gavinaiken** [comment]
Yep should be possible, leave it with me!

**Comment by gavinaiken** [comment]
Do you have a repo for your flickr demo I could fork? Looks like the `gh-pages` branch only has the compiled, bundled version, if you have a raw unbundled version I could set up a demo easily.

**Comment by stoffeastrom** [comment]
it's under the demo branch

**Comment by stoffeastrom** [comment]
I pushed the latest so it should be usable. Haven't updated to the latest Aurelia that is coming right now but will look into it later

**Comment by gavinaiken** [comment]
Here you go, this pretty accurately matches how my app was set up:

https://github.com/oribella/aurelia-sortable/compare/demo...gavinaiken:ga/broken-demo

All you need to do to see the issue is to go to the Flickr demo page, make sure your browser window is short enough to give you vertical scrollbars, then scroll to the bottom and try to drag a widget. Items at the top are fine, or if your window is big enough and you don't have scrollbars it is also fine for all sortable items.

**Comment by stoffeastrom** [comment]
Thanks, I will take a look

**Comment by stoffeastrom** [comment]
@gavinaiken I thought that the `body` was scrolling but according to above it's not. It can be the `window`/`document` that is the scrolling element?

So we have a couple of issues here caused by this

1. We don't detect auto scroll since we don't consider the bounds for `window`

2. For this use case it can't find the sortable items since it uses the `pageX`, `pageY` as you said

3. The scrolling element can't be set to `window`/`document` since the `closest`function only walks up to `document`and then stops matching. This due to the fact that `matchesSelector`only handles `Element`, same for `getBoundingClientRect`

I'm not sure if I want to support this use case since it means a lot of special handling...

Thoughts?

**Comment by gavinaiken** [comment]
Yes, I can see it would mean a lot more code to detect this different case and handle it correctly. For me, it's fine to use the work-around of the `absolute` positioned container. Thanks for looking into it!
